# NumPy Exercises
import numpy 

In [1]:
import numpy as np

Q1. Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

array([1, 3, 5, 7, 9])

In [2]:
odd = np.arange(1,10,2)
odd


array([1, 3, 5, 7, 9])

Q.2. Replace all odd numbers in arr with -1

Desired Output:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q.3. Convert a 1D array to a 2D array with 2 rows


**Input :**

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Desired Output:**

array([[0, 1, 2, 3, 4],

       [5, 6, 7, 8, 9]])

In [20]:
a= np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new= a.reshape(2,5)
new

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q.4. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

**Input:**

a = np.array([1,2,3])

**Desired Output:**

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
a = np.array([1, 2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q.5.  Get the common items between a and b

**Input:**

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

**Desired Output:**

array([2, 4])

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))      
    
    

[2 4]


Q.6. From array a remove all items present in array b

**Input:**

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

**Desired Output:**

array([1,2,3,4])

In [32]:
a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

print(np.setdiff1d(a,b))

[1 2 3 4]


Q.7.  Compute the one-hot encodings (dummy binary variables for each unique value in the array)

Input:

np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
### array([2, 3, 2, 2, 2, 1])
Output:

### array([[ 0.,  1.,  0.],
###                  [ 0.,  0.,  1.],
###        [ 0.,  1.,  0.],
###        [ 0.,  1.,  0.],
###        [ 0.,  1.,  0.],
###        [ 1.,  0.,  0.]])

In [33]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6) 
arr

(arr[:,None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

Q.8.  Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.

Desired Output
### array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [39]:
np.arange(5,33,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])